# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '17.0'
prepare_react_native_project!

# ZeroSettleKit - the underlying iOS SDK
# Option 1: From CocoaPods trunk (once published)
# pod 'ZeroSettleKit', '~> 1.0'
#
# Option 2: From GitHub (recommended until trunk propagates)
pod 'ZeroSettleKit', :git => 'https://github.com/zerosettle/ZeroSettleKit.git', :tag => '1.0.0'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ZeroSettleExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
